### ISSUE TITLE
Can only select Qwant

### ISSUE THREAD

**Issue by da5nsy** [Andrew67/geo-handler#5]
![image](https://github.com/Andrew67/geo-handler/assets/3739866/5d7ec33a-e155-4242-b84f-1de19ce46270)

I assume this dropdown box should have more options?

Firefox 116.0.2, Windows 10, happy to provide other relevant info

**Comment by Andrew67** [comment]
That's weird. Yes I just checked on my macOS machine and it _looks_ like it only shows Qwant, but I can use my scroll wheel inside of it to see the others.
As you expect, my intention was not to only show one drop-down item at a time.
Will have to see what I can do.

**Comment by da5nsy** [comment]
Oh yeah! Can confirm - for me if I use the up/down arrows I can select other options

**Comment by Andrew67** [comment]
<img width="657" alt="Screenshot 2024-09-01 at 00 28 13" src="https://github.com/user-attachments/assets/8c60c810-9694-4f45-88da-5bfaf438be59">

As of Firefox 129 and upcoming version 3.0 for this extension I no longer see this issue. Will re-open if it happens again.
