### ISSUE TITLE
Make geo-handler available on Fennec

### ISSUE THREAD

**Issue by adrienandrem** [Andrew67/geo-handler#6]
Geo-handler is not available for [Fennec](https://f-droid.org/fr/packages/org.mozilla.fennec_fdroid).

## Steps to reproduce

* install [F-Droid](https://f-droid.org)
* install Fennec
* open Fennec
* on a tab, tap Options/Addons/Addons Manager
* on the screen bottom, tap "Discover more"
* on "Search for addons" entry, enter "geo handler" and tap Enter
* there is 0 results.

**Comment by Andrew67** [comment]
From README.md:
> Android already natively [partially supports geo: URIs](https://developer.android.com/guide/appendix/g-app-intents.html)
> Support varies by app, and Firefox for Android passes the URI directly to the OS, so this extension is not compatible
